FROM archlinux/archlinux:base-devel
LABEL maintainer="locietta@qq.com"

RUN echo $'[archlinuxcn]\n\
Server = https://mirrors.ustc.edu.cn/archlinuxcn/$arch\n\
Server = https://mirrors.tuna.tsinghua.edu.cn/archlinuxcn/$arch' >> /etc/pacman.conf\
    && pacman-key --lsign-key "farseerfc@archlinux.org" \
    && pacman -Sy --noconfirm archlinuxcn-keyring \
    && pacman-key --init && pacman-key --populate archlinuxcn\
    && pacman -Syy --noconfirm git python\
    && pacman -Scc --noconfirm && rm -rf /var/cache/pacman/pkg/* && rm -rf /var/lib/pacman/sync/*\
    && rm -rf /usr/share/info/* && rm -rf /usr/share/man/* && rm -rf /usr/share/doc/*\
    && rm -rf /tmp/*
