name: CI to Docker Hub

on:
  push:
    branches: [antlr]
  pull_request:
    branches: [antlr]
  schedule:
    - cron: "0 22 * * 1,4"
  workflow_dispatch:
    # manual trigger
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/loia-dev-base:antlr4
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/loia-dev-base:antlr_cache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/loia-dev-base:antlr_cache,mode=max
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
