name: CI to Docker Hub

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 22 * * *"
  workflow_dispatch:
    # manual trigger
jobs:
  build:
    runs-on: ubuntu-latest

    strategy: 
      matrix:
        include:
          - tag: latest
            dockerfile: dockerfile
          - tag: aur
            dockerfile: aur.dockerfile
          - tag: debian
            dockerfile: debian.dockerfile
          - tag: node
            dockerfile: node.dockerfile
          # - tag: minimal
          #   dockerfile: minimal.dockerfile

    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Login to Docker Hub
        uses: docker/login-action@master
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
      - name: Build and push latest
        id: docker_build
        uses: docker/build-push-action@master
        with:
          context: ./
          file: dockerfiles/${{ matrix.dockerfile }}
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/loia-dev-base:${{ matrix.tag }}
          # cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/loia-dev-base:${{ matrix.tag }}-buildcache
          # cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/loia-dev-base:${{ matrix.tag }}-buildcache,mode=max
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
